export type ShortcutPlatform = 'mac' | 'windows' | 'linux';

export type ShortcutScope =
  | 'global'
  | 'canvas'
  | 'selection'
  | 'schema'
  | 'text-editing'
  | 'navigation'
  | 'view'
  | 'collaboration';

export type ShortcutDefinition = {
  id: string;
  label: string;
  description?: string;
  keys: string[];
  macKeys?: string[];
  windowsKeys?: string[];
  scope: ShortcutScope;
  actionId?: string;
  commandId?: string;
  priority?: 'primary' | 'secondary' | 'danger';
  disabledWhenEditingText?: boolean;
  requiresSelection?: boolean;
  requiresEditableStructure?: boolean;
};

const hasNavigator = typeof navigator !== 'undefined';

export const isMacShortcutPlatform = (platform: ShortcutPlatform) => platform === 'mac';

export const detectShortcutPlatform = (): ShortcutPlatform => {
  if (!hasNavigator) return 'windows';

  const platform = String(navigator.platform || '').toLowerCase();
  const userAgent = String(navigator.userAgent || '').toLowerCase();

  if (platform.includes('mac') || userAgent.includes('mac os')) return 'mac';
  if (platform.includes('linux') || userAgent.includes('linux')) return 'linux';
  return 'windows';
};

const common = {
  copy: {
    id: 'copy',
    label: 'Copiar',
    description: 'Copia la selección actual al portapapeles interno.',
    keys: ['mod+c'],
    macKeys: ['meta+c'],
    windowsKeys: ['ctrl+c'],
    scope: 'selection',
    actionId: 'copy',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresSelection: true,
  } satisfies ShortcutDefinition,
  cut: {
    id: 'cut',
    label: 'Cortar',
    description: 'Copia y elimina la selección actual.',
    keys: ['mod+x'],
    macKeys: ['meta+x'],
    windowsKeys: ['ctrl+x'],
    scope: 'selection',
    actionId: 'cut',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  paste: {
    id: 'paste',
    label: 'Pegar',
    description: 'Inserta el contenido copiado en la pagina activa.',
    keys: ['mod+v'],
    macKeys: ['meta+v'],
    windowsKeys: ['ctrl+v'],
    scope: 'canvas',
    actionId: 'paste',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  duplicate: {
    id: 'duplicate',
    label: 'Duplicar',
    description: 'Duplica la seleccion actual con desplazamiento seguro.',
    keys: ['mod+d'],
    macKeys: ['meta+d'],
    windowsKeys: ['ctrl+d'],
    scope: 'selection',
    actionId: 'duplicate',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  delete: {
    id: 'delete',
    label: 'Eliminar',
    description: 'Elimina la seleccion actual.',
    keys: ['backspace', 'delete'],
    macKeys: ['backspace', 'delete'],
    windowsKeys: ['delete', 'backspace'],
    scope: 'selection',
    actionId: 'delete',
    priority: 'danger',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  undo: {
    id: 'undo',
    label: 'Deshacer',
    description: 'Revierte la ultima accion.',
    keys: ['mod+z'],
    macKeys: ['meta+z'],
    windowsKeys: ['ctrl+z'],
    scope: 'global',
    actionId: 'undo',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  redo: {
    id: 'redo',
    label: 'Rehacer',
    description: 'Repite la ultima accion deshecha.',
    keys: ['mod+shift+z'],
    macKeys: ['meta+shift+z'],
    windowsKeys: ['ctrl+y', 'ctrl+shift+z'],
    scope: 'global',
    actionId: 'redo',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  selectAllVisible: {
    id: 'selectAllVisible',
    label: 'Seleccionar todo',
    description: 'Selecciona todos los campos visibles en la pagina actual.',
    keys: ['mod+a'],
    macKeys: ['meta+a'],
    windowsKeys: ['ctrl+a'],
    scope: 'selection',
    actionId: 'selectAllVisible',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  clearSelection: {
    id: 'clearSelection',
    label: 'Limpiar seleccion',
    description: 'Limpia la seleccion activa.',
    keys: ['escape'],
    macKeys: ['escape'],
    windowsKeys: ['escape'],
    scope: 'global',
    actionId: 'clearSelection',
    priority: 'secondary',
  } satisfies ShortcutDefinition,
  recipientPrevious: {
    id: 'recipientPrevious',
    label: 'Destinatario anterior',
    description: 'Asigna el destinatario anterior a la selección actual.',
    keys: ['mod+shift+comma'],
    macKeys: ['meta+shift+comma'],
    windowsKeys: ['ctrl+shift+comma'],
    scope: 'collaboration',
    actionId: 'recipientPrevious',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  recipientNext: {
    id: 'recipientNext',
    label: 'Destinatario siguiente',
    description: 'Asigna el siguiente destinatario a la selección actual.',
    keys: ['mod+shift+period'],
    macKeys: ['meta+shift+period'],
    windowsKeys: ['ctrl+shift+period'],
    scope: 'collaboration',
    actionId: 'recipientNext',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  moveUp: {
    id: 'moveUp',
    label: 'Mover arriba',
    description: 'Mueve la seleccion hacia arriba.',
    keys: ['arrowup', 'shift+arrowup', 'alt+arrowup', 'mod+arrowup'],
    macKeys: ['arrowup', 'shift+arrowup', 'alt+arrowup', 'meta+arrowup'],
    windowsKeys: ['arrowup', 'shift+arrowup', 'alt+arrowup', 'ctrl+arrowup'],
    scope: 'selection',
    actionId: 'moveUp',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  moveDown: {
    id: 'moveDown',
    label: 'Mover abajo',
    description: 'Mueve la seleccion hacia abajo.',
    keys: ['arrowdown', 'shift+arrowdown', 'alt+arrowdown', 'mod+arrowdown'],
    macKeys: ['arrowdown', 'shift+arrowdown', 'alt+arrowdown', 'meta+arrowdown'],
    windowsKeys: ['arrowdown', 'shift+arrowdown', 'alt+arrowdown', 'ctrl+arrowdown'],
    scope: 'selection',
    actionId: 'moveDown',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  moveLeft: {
    id: 'moveLeft',
    label: 'Mover izquierda',
    description: 'Mueve la seleccion hacia la izquierda.',
    keys: ['arrowleft', 'shift+arrowleft', 'alt+arrowleft', 'mod+arrowleft'],
    macKeys: ['arrowleft', 'shift+arrowleft', 'alt+arrowleft', 'meta+arrowleft'],
    windowsKeys: ['arrowleft', 'shift+arrowleft', 'alt+arrowleft', 'ctrl+arrowleft'],
    scope: 'selection',
    actionId: 'moveLeft',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  moveRight: {
    id: 'moveRight',
    label: 'Mover derecha',
    description: 'Mueve la seleccion hacia la derecha.',
    keys: ['arrowright', 'shift+arrowright', 'alt+arrowright', 'mod+arrowright'],
    macKeys: ['arrowright', 'shift+arrowright', 'alt+arrowright', 'meta+arrowright'],
    windowsKeys: ['arrowright', 'shift+arrowright', 'alt+arrowright', 'ctrl+arrowright'],
    scope: 'selection',
    actionId: 'moveRight',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  openDetail: {
    id: 'openDetail',
    label: 'Abrir detalle',
    description: 'Abre el panel contextual del elemento seleccionado.',
    keys: ['enter'],
    macKeys: ['enter'],
    windowsKeys: ['enter'],
    scope: 'schema',
    actionId: 'openDetail',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
  } satisfies ShortcutDefinition,
  openShortcuts: {
    id: 'openShortcuts',
    label: 'Atajos',
    description: 'Abre el panel de atajos del diseñador.',
    keys: ['mod+slash', 'question'],
    macKeys: ['meta+slash', 'question'],
    windowsKeys: ['ctrl+slash', 'question'],
    scope: 'global',
    actionId: 'openShortcuts',
    priority: 'primary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  addComment: {
    id: 'addComment',
    label: 'Agregar comentario',
    description: 'Crea un comentario para el schema activo.',
    keys: ['a'],
    macKeys: ['a'],
    windowsKeys: ['a'],
    scope: 'collaboration',
    actionId: 'addComment',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  toggleLock: {
    id: 'toggleLock',
    label: 'Bloquear / desbloquear',
    description: 'Alterna el estado de bloqueo del schema seleccionado.',
    keys: ['l'],
    macKeys: ['l'],
    windowsKeys: ['l'],
    scope: 'collaboration',
    actionId: 'toggleLock',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  zoomIn: {
    id: 'zoomIn',
    label: 'Acercar',
    description: 'Incrementa el zoom de la vista.',
    keys: ['mod+plus', 'mod+equal'],
    macKeys: ['meta+plus', 'meta+equal'],
    windowsKeys: ['ctrl+plus', 'ctrl+equal'],
    scope: 'view',
    actionId: 'zoomIn',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  zoomOut: {
    id: 'zoomOut',
    label: 'Alejar',
    description: 'Reduce el zoom de la vista.',
    keys: ['mod+minus', 'mod+hyphen'],
    macKeys: ['meta+minus', 'meta+hyphen'],
    windowsKeys: ['ctrl+minus', 'ctrl+hyphen'],
    scope: 'view',
    actionId: 'zoomOut',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  fitPage: {
    id: 'fitPage',
    label: 'Ajustar pagina',
    description: 'Ajusta la pagina al viewport.',
    keys: ['mod+0'],
    macKeys: ['meta+0'],
    windowsKeys: ['ctrl+0'],
    scope: 'view',
    actionId: 'fitPage',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  zoom100: {
    id: 'zoom100',
    label: 'Zoom 100%',
    description: 'Restablece la vista al 100%.',
    keys: ['mod+1'],
    macKeys: ['meta+1'],
    windowsKeys: ['ctrl+1'],
    scope: 'view',
    actionId: 'zoom100',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  fitWidth: {
    id: 'fitWidth',
    label: 'Ajustar ancho',
    description: 'Ajusta el ancho de la pagina al viewport.',
    keys: ['mod+2'],
    macKeys: ['meta+2'],
    windowsKeys: ['ctrl+2'],
    scope: 'view',
    actionId: 'fitWidth',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  previousPage: {
    id: 'previousPage',
    label: 'Pagina anterior',
    description: 'Navega a la pagina anterior.',
    keys: ['pageup'],
    macKeys: ['pageup'],
    windowsKeys: ['pageup'],
    scope: 'navigation',
    actionId: 'previousPage',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  nextPage: {
    id: 'nextPage',
    label: 'Pagina siguiente',
    description: 'Navega a la pagina siguiente.',
    keys: ['pagedown'],
    macKeys: ['pagedown'],
    windowsKeys: ['pagedown'],
    scope: 'navigation',
    actionId: 'nextPage',
    priority: 'secondary',
    disabledWhenEditingText: true,
  } satisfies ShortcutDefinition,
  insertText: {
    id: 'insertText',
    label: 'Insertar texto',
    description: 'Inserta un campo de texto.',
    keys: ['t'],
    macKeys: ['t'],
    windowsKeys: ['t'],
    scope: 'canvas',
    actionId: 'insertText',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertSignature: {
    id: 'insertSignature',
    label: 'Insertar firma',
    description: 'Inserta un campo de firma.',
    keys: ['s'],
    macKeys: ['s'],
    windowsKeys: ['s'],
    scope: 'canvas',
    actionId: 'insertSignature',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertInitial: {
    id: 'insertInitial',
    label: 'Insertar iniciales',
    description: 'Inserta un campo de iniciales.',
    keys: ['i'],
    macKeys: ['i'],
    windowsKeys: ['i'],
    scope: 'canvas',
    actionId: 'insertInitial',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertName: {
    id: 'insertName',
    label: 'Insertar nombre',
    description: 'Inserta un campo de nombre.',
    keys: ['n'],
    macKeys: ['n'],
    windowsKeys: ['n'],
    scope: 'canvas',
    actionId: 'insertName',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertEmail: {
    id: 'insertEmail',
    label: 'Insertar email',
    description: 'Inserta un campo de email.',
    keys: ['e'],
    macKeys: ['e'],
    windowsKeys: ['e'],
    scope: 'canvas',
    actionId: 'insertEmail',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertDate: {
    id: 'insertDate',
    label: 'Insertar fecha',
    description: 'Inserta un campo de fecha.',
    keys: ['d'],
    macKeys: ['d'],
    windowsKeys: ['d'],
    scope: 'canvas',
    actionId: 'insertDate',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertCheckbox: {
    id: 'insertCheckbox',
    label: 'Insertar checkbox',
    description: 'Inserta un campo de checkbox.',
    keys: ['c'],
    macKeys: ['c'],
    windowsKeys: ['c'],
    scope: 'canvas',
    actionId: 'insertCheckbox',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertRadio: {
    id: 'insertRadio',
    label: 'Insertar radio',
    description: 'Inserta un campo de radio.',
    keys: ['r'],
    macKeys: ['r'],
    windowsKeys: ['r'],
    scope: 'canvas',
    actionId: 'insertRadio',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  insertSelect: {
    id: 'insertSelect',
    label: 'Insertar desplegable',
    description: 'Inserta un campo de lista desplegable.',
    keys: ['m'],
    macKeys: ['m'],
    windowsKeys: ['m'],
    scope: 'canvas',
    actionId: 'insertSelect',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  group: {
    id: 'group',
    label: 'Agrupar',
    description: 'Agrupa los campos seleccionados en un grupo visual.',
    keys: ['mod+g'],
    macKeys: ['meta+g'],
    windowsKeys: ['ctrl+g'],
    scope: 'selection',
    actionId: 'group',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  ungroup: {
    id: 'ungroup',
    label: 'Desagrupar',
    description: 'Desagrupa el grupo seleccionado.',
    keys: ['mod+shift+g'],
    macKeys: ['meta+shift+g'],
    windowsKeys: ['ctrl+shift+g'],
    scope: 'selection',
    actionId: 'ungroup',
    priority: 'primary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
  showInspector: {
    id: 'showInspector',
    label: 'Mostrar inspector',
    description: 'Abre el inspector contextual del campo seleccionado.',
    keys: ['mod+shift+i'],
    macKeys: ['meta+shift+i'],
    windowsKeys: ['ctrl+shift+i'],
    scope: 'selection',
    actionId: 'showInspector',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
  } satisfies ShortcutDefinition,
  copyStyle: {
    id: 'copyStyle',
    label: 'Copiar estilo',
    description: 'Copia las propiedades de estilo del campo seleccionado.',
    keys: ['mod+shift+c'],
    macKeys: ['meta+shift+c'],
    windowsKeys: ['ctrl+shift+c'],
    scope: 'selection',
    actionId: 'copyStyle',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
  } satisfies ShortcutDefinition,
  pasteStyle: {
    id: 'pasteStyle',
    label: 'Pegar estilo',
    description: 'Aplica el estilo copiado al campo seleccionado.',
    keys: ['mod+shift+d'],
    macKeys: ['meta+shift+d'],
    windowsKeys: ['ctrl+shift+d'],
    scope: 'selection',
    actionId: 'pasteStyle',
    priority: 'secondary',
    disabledWhenEditingText: true,
    requiresSelection: true,
    requiresEditableStructure: true,
  } satisfies ShortcutDefinition,
} as const;

export const DESIGNER_SHORTCUTS: ShortcutDefinition[] = Object.values(common);
