/**
 * dateSigned schema — automatically populated with the signing date.
 * readOnly: true. Cannot be edited by recipient.
 * Appearance: text-like rendering (date formatted string).
 * Auto-populates when a co-located signature field is signed.
 */
import { CalendarCheck } from 'lucide-react';
import { renderLucideIcon } from '../schemaBuilder.js';
import { createSigningSchemaPlugin } from './signingSchemaFactory.js';

const DATE_FORMAT_OPTIONS: Array<{ label: string; value: string }> = [
  { label: 'DD/MM/AAAA', value: 'dd/MM/yyyy' },
  { label: 'MM/DD/AAAA', value: 'MM/dd/yyyy' },
  { label: 'AAAA-MM-DD', value: 'yyyy-MM-dd' },
  { label: 'D de Mes de AAAA', value: "d 'de' MMMM 'de' yyyy" },
  { label: 'Mes D, AAAA', value: 'MMMM d, yyyy' },
];

const dateSignedPlugin = createSigningSchemaPlugin({
  type: 'dateSigned',
  label: 'Fecha de firma',
  placeholder: 'Fecha de firma',
  readonly: true,
  autoGenerated: true,
  category: 'Firma',
  tags: ['date', 'signature', 'signing', 'auto'],
  icon: renderLucideIcon(CalendarCheck, { stroke: '#374151' }),
  propPanelFields: () => ({
    dateFormat: {
      title: 'Formato de fecha',
      type: 'string',
      widget: 'select',
      span: 12,
      props: { options: DATE_FORMAT_OPTIONS },
    },
    dateLocale: {
      title: 'Idioma',
      type: 'string',
      widget: 'select',
      span: 12,
      props: {
        options: [
          { label: 'Español', value: 'es' },
          { label: 'English', value: 'en' },
          { label: 'Français', value: 'fr' },
          { label: 'Português', value: 'pt' },
        ],
      },
    },
    autoPopulateFrom: {
      title: 'Llenar desde',
      type: 'string',
      widget: 'input',
      span: 12,
      props: { placeholder: 'nombre del campo firma (vacío = automático)' },
    },
  }),
  propPanelPropertyMap: {
    dateFormat: 'data',
    dateLocale: 'data',
    autoPopulateFrom: 'data',
  },
  defaultSchemaOverrides: {
    position: { x: 0, y: 0 },
    width: 35,
    height: 7,
    dateFormat: 'dd/MM/yyyy',
    dateLocale: 'es',
    autoPopulateFrom: '',
    fontSize: 10,
    fontColor: '#374151',
  },
});

export default dateSignedPlugin;
