import { cloneDeep } from '@sisad-pdfme/common';
import type { Plugin, Schema } from '@sisad-pdfme/common';
import text from '@sisad-pdfme/schemas/text';
import { createSchemaPlugin } from '@sisad-pdfme/schemas/schemaBuilder';
import { createSchemaInspectorConfig } from '@sisad-pdfme/schemas/schemaFamilies';
import {
  basicsFields,
  helpFields,
  dataLabelFields,
  COMMON_PROPERTY_MAP,
} from '@sisad-pdfme/schemas/propPanel/commonInspectorFields';
import type { PropPanelSchema } from '@sisad-pdfme/common';
import type { PropPanelInspectorSectionKey } from '@sisad-pdfme/common/types';
import type { SchemaCapability } from '@sisad-pdfme/schemas/schemaBuilder';

type SigningSchemaKind = 'signature' | 'initials' | 'dateSigned';

export type SigningSchemaFactoryConfig = {
  type: SigningSchemaKind;
  label: string;
  placeholder: string;
  readonly?: boolean;
  autoGenerated?: boolean;
  category?: string;
  tags: string[];
  /** renderLucideIcon returns string | SVGElement; factory serializes SVGElement. */
  icon: string | SVGElement;
  /** Schema-specific propPanel fields (date format, locale, etc). */
  propPanelFields: () => Record<string, PropPanelSchema>;
  /** Inspector property map for schema-specific fields. */
  propPanelPropertyMap: Partial<Record<string, PropPanelInspectorSectionKey>>;
  /** Merged over text.propPanel.defaultSchema. Defaults to read-only for auto-generated variants. */
  defaultSchemaOverrides: Record<string, unknown>;
  /** Optional runtime renderers; defaults to text.ui/text.pdf. */
  ui?: typeof text.ui;
  pdf?: typeof text.pdf;
  /** Optional plugin capabilities. Defaults to the content-oriented text preset. */
  capabilities?: SchemaCapability[];
};

/**
 * Creates a signing Plugin<Schema> with text-rendered defaults.
 * Defaults to text.ui/text.pdf, but callers can override the renderers
 * when they want to reuse the same factory for other signing surfaces.
 */
export function createSigningSchemaPlugin(config: SigningSchemaFactoryConfig): Plugin<Schema> {
  const {
    type,
    label,
    placeholder,
    readonly = false,
    autoGenerated = false,
    category = 'Firma',
    tags,
    icon,
    propPanelFields,
    propPanelPropertyMap,
    defaultSchemaOverrides,
    ui = text.ui,
    pdf = text.pdf,
    capabilities = ['designer', 'form', 'viewer', 'content'],
  } = config;

  const normalizedIcon: string =
    typeof icon === 'string' ? icon : (icon as SVGElement).outerHTML;
  const baseDefaultSchema = cloneDeep(text.propPanel.defaultSchema) as Record<string, unknown>;
  const defaultSchema = {
    ...baseDefaultSchema,
    name: '',
    type,
    content: '',
    placeholderText: placeholder,
    readOnly: readonly || autoGenerated,
    autoGenerated,
    required: false,
    ...defaultSchemaOverrides,
  } as unknown as Schema;

  return createSchemaPlugin<Schema>(
    {
      ui,
      pdf,
      propPanel: {
        schema: (): Record<string, PropPanelSchema> => ({
          // Las variantes autogeneradas (p. ej. fecha de firma) se rellenan
          // solas: exponen obligatoriedad pero no el switch de solo lectura,
          // que forma parte de su definición.
          ...(autoGenerated ? { required: basicsFields().required } : basicsFields()),
          ...propPanelFields(),
          ...helpFields(),
          ...dataLabelFields(),
        }),
        inspector: createSchemaInspectorConfig('textual', {
          propertyMap: {
            ...COMMON_PROPERTY_MAP,
            ...propPanelPropertyMap,
          },
        }),
        defaultSchema,
      },
      icon: normalizedIcon,
    },
    {
      key: type,
      type,
      label,
      category,
      tags,
      capabilities,
    },
  );
}

/**
 * Backward-compatible alias kept for the existing dateSigned import path.
 */
export function createTextSigningSchemaPlugin(config: Omit<SigningSchemaFactoryConfig, 'placeholder'> & {
  placeholder?: string;
}): Plugin<Schema> {
  return createSigningSchemaPlugin({
    ...config,
    placeholder: config.placeholder || config.label,
  });
}
