#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path';
import {assertSafeTargets,backupFile,backupRootFor,ensureDir,parseArgs,readJson,sha256File,writeJson} from './core.mjs';
const {root,apply}=parseArgs(); const testingRoot=path.resolve(import.meta.dirname,'..'); const overlayRoot=path.join(testingRoot,'test-quality-overlays'); const overlayFor=rel=>path.join(overlayRoot,rel);
const plan=[];
const numberRel='tests/number-input.spec.ts', numberAbs=path.join(root,numberRel);
if(fs.existsSync(numberAbs)){const t=fs.readFileSync(numberAbs,'utf8'); if(/removeAllRanges/.test(t)&&/page\.keyboard\.type/.test(t))plan.push({action:'REPLACE',path:numberRel,reason:'FALSE_POSITIVE_HARNESS'}); else if(/pressSequentially/.test(t)&&/control positivo: acepta dígitos/.test(t))plan.push({action:'SKIP',path:numberRel,reason:'ALREADY_CANONICAL'}); else plan.push({action:'BLOCK',path:numberRel,reason:'UNKNOWN_NUMBER_TEST_SHAPE'});} else plan.push({action:'BLOCK',path:numberRel,reason:'MISSING_NUMBER_TEST'});
const unitRel='tests/unit/sisad-pdfme-comprehensive/contracts/schemas/numberInputPolicy.behavior.test.ts', unitAbs=path.join(root,unitRel); if(!fs.existsSync(unitAbs))plan.push({action:'CREATE',path:unitRel,reason:'NUMBER_BEHAVIOR_CONTRACT'}); else {const source=overlayFor(unitRel),same=fs.existsSync(source)&&fs.readFileSync(source,'utf8')===fs.readFileSync(unitAbs,'utf8'); plan.push({action:same?'SKIP':'BLOCK',path:unitRel,reason:same?'ALREADY_INSTALLED':'EXISTING_DIFFERENT_TEST'});}
const pwRel='playwright.config.ts', pwAbs=path.join(root,pwRel); if(fs.existsSync(pwAbs)){const t=fs.readFileSync(pwAbs,'utf8'); if(/\['json'\]/.test(t)&&!/outputFile/.test(t))plan.push({action:'PATCH',path:pwRel,reason:'JSON_REPORTER_TO_FILE'}); else plan.push({action:'SKIP',path:pwRel,reason:'REPORTER_ALREADY_SAFE_OR_CUSTOM'});}
const countRel='scripts/testing/count-sisad-pdfme-tests.mjs', countAbs=path.join(root,countRel); if(fs.existsSync(countAbs)){const t=fs.readFileSync(countAbs,'utf8'); plan.push({action:/minimum\s*:\s*1000|cases\s*>=\s*1000/.test(t)?'REPLACE':'SKIP',path:countRel,reason:/minimum\s*:\s*1000|cases\s*>=\s*1000/.test(t)?'REMOVE_RAW_COUNT_GATE':'NO_RAW_COUNT_GATE'});} else plan.push({action:'CREATE',path:countRel,reason:'LAYERED_TEST_INVENTORY'});
const jsRel='playwright.config.js',jsAbs=path.join(root,jsRel); if(fs.existsSync(jsAbs)&&fs.existsSync(pwAbs)){const js=fs.readFileSync(jsAbs,'utf8'),pkg=readJson(path.join(root,'package.json'),{}),ref=JSON.stringify(pkg?.scripts??{}).includes('playwright.config.js'),legacy=/\/\/\s*baseURL|\/\/\s*webServer|localhost:3000/.test(js); plan.push({action:!ref&&legacy?'DELETE':'BLOCK',path:jsRel,reason:!ref&&legacy?'SUPERSEDED_PLAYWRIGHT_CONFIG':'CONFIG_REQUIRES_REVIEW'});}
console.log(JSON.stringify({root,apply,plan},null,2)); if(!apply)process.exit(0); const blocking=plan.filter(x=>x.action==='BLOCK'); if(blocking.length)throw new Error('APPLY_BLOCKED\n'+blocking.map(x=>`${x.path}: ${x.reason}`).join('\n'));
const targets=plan.filter(x=>['REPLACE','PATCH','DELETE'].includes(x.action)).map(x=>x.path); assertSafeTargets(root,targets); const backups=[],after=[];
for(const item of plan){const rel=item.path,abs=path.join(root,rel); if(['REPLACE','PATCH','DELETE'].includes(item.action)&&fs.existsSync(abs)){const b=backupFile(root,rel); if(b)backups.push(b);} if(item.action==='REPLACE'||item.action==='CREATE'){const src=overlayFor(rel); if(!fs.existsSync(src))throw new Error(`MISSING_OVERLAY: ${rel}`); ensureDir(path.dirname(abs)); fs.copyFileSync(src,abs); after.push({path:rel,afterHash:sha256File(abs),created:item.action==='CREATE'});} if(item.action==='PATCH'&&rel===pwRel){let t=fs.readFileSync(abs,'utf8'); t=t.replace(/reporter:\s*\[\s*\['json'\]\s*,\s*\['list'\]\s*\],?/m,"reporter: [['list'], ['json', { outputFile: 'test-results/results.json' }]],"); t=t.replace(/reporter:\s*\[\s*\['list'\]\s*,\s*\['json'\]\s*\],?/m,"reporter: [['list'], ['json', { outputFile: 'test-results/results.json' }]],"); fs.writeFileSync(abs,t,'utf8'); after.push({path:rel,afterHash:sha256File(abs)});} if(item.action==='DELETE'){fs.rmSync(abs,{force:true}); after.push({path:rel,deleted:true});}}
writeJson(path.join(root,'config/tooling/test-quality.apply.json'),{backupRoot:backupRootFor(root),backups,after}); console.log('TEST_QUALITY_APPLY_OK');
